// Auto generated by X compiler.
#pragma region X_STANDARD_IMPORTS
#include <iostream>
#include <locale.h>
#pragma endregion X_STANDARD_IMPORTS

#pragma region X_BUILTIN_FUNCTIONS
template <typename any>
inline void out(any v) {
  std::wcout << v;
}

template <typename any>
inline void outln(any v) {
  out(v);
  std::wcout << std::endl;
}
#pragma endregion X_BUILTIN_FUNCTIONS

#pragma region X_GLOBAL_VARIABLES
auto a = 9;
auto b = a * 2;
#pragma endregion X_GLOBAL_VARIABLES

#pragma region X_FUNCTIONS
inline void printInt(int a) {
  outln(a);
}

int main() {
#pragma region X_ENTRY_POINT_STANDARD_CODES
  setlocale(0x0, "");
#pragma endregion


  auto a = true;
  bool b = false;
  outln(5 > 43);
  printInt(5 + ~(2^5));
}

#pragma endregion X_FUNCTIONS