name: Std Tests [Clang] - Windows
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-exec:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Compiler
        run: |
          mkdir bin
          clang++ -fwrapv -O0 --std=c++17 -Wno-everything -o bin/julec.exe ir.cpp -lws2_32 -lshell32

      - name: Test Program
        run: |
          .\bin\julec -t --compiler clang -o test .
          gc dist\ir.cpp
          .\bin\julec --compiler clang -o test .
          ./test
