name: Std Tests [GCC] - Windows
on: [push, pull_request]

jobs:
  build-and-exec:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get IR
        shell: bash
        run: |
          curl -o ir.cpp https://raw.githubusercontent.com/julelang/julec-ir/main/src/windows-amd64.cpp
      - name: Build Jule Compiler
        shell: bash
        run: |
          mkdir bin
          clang++ -Wno-everything --std=c++17 -fwrapv -ffloat-store -fno-fast-math -fno-rounding-math -ffp-contract=fast -O0 -flto=thin -fuse-ld=lld -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -o bin/julec.exe ir.cpp -lws2_32 -lshell32 -liphlpapi -lsynchronization
      - name: Add Compiler to the PATH
        shell: bash
        run: |
          echo "export PATH=\$PATH:./bin/" >> $GITHUB_PATH

      - name: Test - std/net
        run: |
          .\bin\julec test --compiler gcc -o test std/net
          ./test