name: Tests [Clang] - Ubuntu
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julelang/ci@main

      - name: Test - Standard Library
        run: |
          julec --compiler clang -o test tests/std
          ./test

      - name: Test - Aliasing
        run: |
          julec --compiler clang -o test tests/aliasing
          ./test

      - name: Test - Arrays
        run: |
          julec --compiler clang -o test tests/arrays
          ./test

      - name: Test - Basic Calculator
        run: |
          julec --compiler clang -o test tests/basic_calculator

      - name: Test - Channels
        run: |
          julec --compiler clang -o test tests/channels
          ./test

      - name: Test - Comptime
        run: |
          julec --compiler clang -o test tests/comptime
          ./test

      - name: Test - Concurrency
        run: |
          julec --compiler clang -o test tests/concurrency
          ./test

      - name: Test - Exceptionals
        run: |
          julec --compiler clang -o test tests/exceptionals
          ./test

      - name: Test - Generics
        run: |
          julec --compiler clang -o test tests/generics
          ./test

      - name: Test - Levenshtein Distance
        run: |
          julec --compiler clang -o test tests/levenshtein_distance
          ./test

      - name: Test - Maps
        run: |
          julec --compiler clang -o test tests/maps
          ./test

      - name: Test - QuickSort
        run: |
          julec --compiler clang -o test tests/quicksort
          ./test

      - name: Test - Sleep
        run: |
          julec --compiler clang -o test tests/sleep
          ./test

      - name: Test - Syntax
        run: |
          julec --compiler clang -o test tests/syntax
          ./test

      - name: Test - Traits
        run: |
          julec --compiler clang -o test tests/traits
          ./test
